name: Proxy Workflow
    
on:
  workflow_dispatch:

concurrency:
  group: proxy
  cancel-in-progress: true

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --login-server=https://vpn.system.payhawk.com --advertise-exit-node --advertise-tags=tag:exit --hostname=exit --accept-routes=false --accept-dns=false

      - name: Sleep
        run: sleep 6h
        timeout-minutes: 360
